
image: gitpod/workspace-full

ports:
  - port: 8080
    visibility: public
    onOpen: open-preview

tasks:
  - name: Start Spring Boot Manually
    init: echo ">>> Start your app using: mvn spring-boot:run"
